---
date: 2018-02-06

title: Title
subtitle: Subtitle

author: Eric M. Fink
affiliation: Elon Law School 

indent: true
# delete for no paragraph indent 

raggedright: true 
#delete for justified paragraphs

numbersections: true
#delete for unnumbered headings 

linkcolors: true
# delete for no colored links 

output: 
  pdf_document:
    latex_engine: xelatex
    template: default.latex
    
---