---
date: 2018-02-06

title: Title
subtitle: Subtitle

author: Eric M. Fink
affiliation: Elon Law School 

indent: true
header: true
footer: true
colorlinks: true

output: 
  pdf_document:
    latex_engine: xelatex
    template: default.latex
    
---