---
date: 2018-02-06

title: Title
subtitle: Subtitle

path: /folder/file.ext # delete for no path in footer 

author: Eric M. Fink
affiliation: Elon Law School 

#-------------------------------------
# Styling Options: Delete for Defaults 
#-------------------------------------

# typography & layout 
fontsize: 10pt # default is 11pt
indent: true 
secnumdepth: 3 # default is 0
spacing: doublespacing # onehalfspacing; default is singlespacing
plainlinks: true # default is colored links; use 'linkcolor:' variable to specify color

output: 
  pdf_document:
    latex_engine: xelatex
    template: default.tex
    
---
