---
date: 2018-02-06

path: # delete for no path in footer 

title: Title
subtitle: Subtitle

author: Eric M. Fink
affiliation: Elon Law School 

# options 
indent: true # delete for no indent 
secnumdepth: 3 # delete for unnumbered headings
spacing: doublespacing # onehalfspacing; delete for singlespacing 
colorlinks: true # delete for no colored links 

output: 
  pdf_document:
    latex_engine: xelatex
    template: default.latex
    
---