---
date: 2018-02-06

path: # delete for no path in footer 

title: Title
subtitle: Subtitle

author: Eric M. Fink
affiliation: Elon Law School 

# options: delete for defaults
fontsize: 10pt # default is 11pt
notes: true
exam: true
largetitle: true
indent: true 
secnumdepth: 3 # default is 0
spacing: doublespacing # onehalfspacing; default is singlespacing=
colorlinks: true 

output: 
  pdf_document:
    latex_engine: xelatex
    template: default.tex
    
---
