---
date: 

title: 'Title'
subtitle: 'Subtitle'

author: Eric M. Fink
position: Associate Professor of Law
affiliation: Elon Law School 
address: Greensboro, North Carolina
email: efink@elon.edu
phone: '+1 336.278.9334'

nohead: true # delete for default header & footer 

linespacing: DoubleSpacing # OnehalfSpacing; delete for SingleSpacing

secnumdepth: 3 # delete for unnumbered section headings 

# delete for defaults
setspace: '1.1'
parindent: 0em
parskip: 0.5em 
listdepth: 6
listmargin: 0em
itemsep: 0em
itemskip: 0em
itemindent: 0em
columnsep: 10mm

# delete for default margins
lr: 1.25in
top: 1in
bottom: 1in 
headheight: 11pt
headdrop: '*'
headsep: '7mm'
headratio: '*'

# delete for default fonts 
fontsize: 11pt
mainfont: 'Cormorant Garamond'
scfont: 'Cormorant SC'
sansfont: 'Proza Libre'
monofont: 'Cousine'
monofontscale: '1.0'
titlefont: '$sansfont$'
titlecolor: 'mydarkred'
titlesize: 'Huge'
subtitlesize: 'huge'
authorsize: normalsize
datesize: normalsize
 
# delete for default chapter headings 
chapter: 'Alegreya Sans Bold' 
chaptercolor: 'mydarkred'
chaptersize: HUGE
chapterskip: 0em

# delete for default section headings 
h1: LARGE
h1bef: 2em
h1aft: 0.2em
h1font: '$sansfont$'
h1color: 'mydarkred'
h2: Large
h2bef: 2em
h2aft: 0.2em
h2font: '$sansfont$'
h2color: 'myblack'
h3: large
h3bef: 2em
h3aft: 0.2em
h3font: '$sansfont$'
h32color: 'myblack'
h4: normalsize
h4bef: 0em
h4aft: 0.2em
h4font: '$mainfont$'
h4color: 'myblack'
h5: normalsize
h5bef: 0em
h5aft: 0.2em
h5font: '$mainfont$'
h5color: 'myblack'


# delete for no table of contents 
toc: true 
toc-depth: 4
listings: 
CustomBullets: 

output:
  pdf_document:
    latex_engine: xelatex
    template: default_memoir.latex

---
